services:
  - type: web
    name: spectraconvert-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: VITE_PAYPAL_ENVIRONMENT
        value: live
      - key: APP_URL
        value: https://spectraconvertonline.netlify.app
      - key: ALLOWED_ORIGINS
        value: https://spectraconvertonline.netlify.app,http://127.0.0.1:3000,http://localhost:3000
      - key: GOOGLE_CLIENT_ID
        value: 920941311246-lficdku6lpv2n81hjtdh5l84039avibi.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: GOOGLE_REDIRECT_URI
        value: https://spectraconvert-api.onrender.com/api/auth/google/callback