services:
  - type: web
    name: spectraconvert-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: VITE_PAYPAL_ENVIRONMENT
        value: live
      - key: APP_URL
        value: https://spectraconvertonline.netlify.app
      - key: ALLOWED_ORIGINS
        value: https://spectraconvertonline.netlify.app,http://127.0.0.1:3000,http://localhost:3000
      - key: GOOGLE_CLIENT_ID
        value: 920941311246-5f5rv8f6m05tgamq5jp4vb3b5u56m40r.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: GOOGLE_REDIRECT_URI
        value: https://spectraconvert-api.onrender.com/api/auth/google/callback